import "./globals.css";
import type { Metadata } from "next";
import { Inter, Miriam_Libre } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const miriam_libre = Miriam_Libre({
  subsets: ["latin", "latin-ext", "hebrew"],
  weight: ["700"],
  variable: "--font-miriam-libre",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${miriam_libre.variable}`}>
        {children}
      </body>
    </html>
  );
}
